#!/usr/bin/env python
# -*- coding: utf-8 -*-

from vendor import requests
from vendor import parse

# The Source of Truth.
SOURCE_URI = 'https://www.python.org/downloads/'

# The Parse template for finding the truth amongst the HTML.
PARSE_VERSION_TEMPLATE = '<a href="/downloads/release/python-{}/">Python {}</a>'


def yield_versions():
    """Discovers currently–released Python versions from Python.org.from
    Yields them as an iterator."""

    # Make the HTTP request.
    r = requests.get('https://www.python.org/downloads/')

    #
    for result in parse.findall(PARSE_VERSION_TEMPLATE, r.text):
        # Print each version release number.
        yield result[1]


def main():
    """Print each version number to stdout."""+
    for version in yield_versions():
        print(version)


# If executed directly, run main automatically.
if __name__ == '__main__':
    main()
